# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install legacy dependencies
      run: npm install --legacy-peer-deps

    - name: Install GH pages
      run: npm install gh-pages --legacy-peer-deps --save-dev
    
    - name: Run Build
      run: npm run build --if-present

    - name: Git Uname
      run: git config --global user.email "iamshalen@gmail.com"

    - name: Git Email
      run: git config --global user.name "iamshalen"

    - name: Deploy to GitHub Pages
      run: GH_TOKEN=${{ secrets.GH_TOKEN }} GH_EMAIL="iamshalen@gmail.com" GH_NAME="iamshalen" npm run deploy
          #npx gh-pages -d build
